apiVersion: apps/v1
kind: Deployment
metadata:
  name: nettool-deployment
  labels:
    app: nettool
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nettool
  template:
    metadata:
      labels:
        app: nettool
    spec:
      containers:
      - name: nettool
        image: nettool:v2
